version: '3'
services:
  app:
    image: percytataje10/orbis-training-docker:2.0
    ports:
      - 1042:3030
      - 35729:35729
    volumes:
      - $PWD:/app
    working_dir: /app
    command: npm start
